name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: echo First Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo Second Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo Third Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo Fourth Hello ${{ inputs.who-to-greet }}.
      shell: bash
